<a href="https://colab.research.google.com/github/DanielYaari28/AIPI510P1/blob/daniel-final-ranking/notebooks/03_final_ranking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd

url = "https://raw.githubusercontent.com/DanielYaari28/AIPI510P1/refs/heads/main/data/engineered_college_data.csv"
df = pd.read_csv(url)

In [8]:
df.columns

Index(['UNITID', 'INSTNM', 'STABBR', 'CONTROL', 'UGDS', 'C150_4', 'RET_FT4',
       'NPT4_PUB', 'NPT4_PRIV', 'DEBT_MDN', 'COSTT4_A', 'MD_EARN_WNE_P10',
       'PCTPELL', 'ADM_RATE', 'NET_PRICE', 'STUDENT_SUCCESS',
       'DEBT_TO_EARNINGS', 'EARNINGS_PERCENTILE', 'DEBT_BURDEN_PERCENTILE',
       'OUTCOME_SCORE', 'AFFORDABILITY_PERCENTILE',
       'ACCESSIBILITY_PERCENTILE'],
      dtype='object')

In [9]:
df["STUDENT_SUCCESS_PERCENTILE"] = df["STUDENT_SUCCESS"].rank(
    pct=True,
    ascending=True
)

In [10]:
df["FINAL_SCORE"] = (
    df["STUDENT_SUCCESS_PERCENTILE"] * 0.40
    + df["OUTCOME_SCORE"] * 0.35
    + df["AFFORDABILITY_PERCENTILE"] * 0.20
    + df["ACCESSIBILITY_PERCENTILE"] * 0.05
)

In [11]:
final_ranking = (
    df
    .sort_values("FINAL_SCORE", ascending=False)
    .head(10)
    [[
        "INSTNM",
        "STUDENT_SUCCESS_PERCENTILE",
        "OUTCOME_SCORE",
        "AFFORDABILITY_PERCENTILE",
        "ACCESSIBILITY_PERCENTILE",
        "FINAL_SCORE"
    ]]
)

final_ranking

,INSTNM,STUDENT_SUCCESS_PERCENTILE,OUTCOME_SCORE,AFFORDABILITY_PERCENTILE,ACCESSIBILITY_PERCENTILE,FINAL_SCORE
393,Princeton University,1.000000,0.993804,0.971499,0.198265,0.952045
48,University of California-Berkeley,0.967782,0.968030,0.753408,0.455390,0.899374
51,University of California-Los Angeles,0.969021,0.919207,0.811029,0.442379,0.893656
760,Stanford University,0.966543,0.998513,0.737299,0.195787,0.893346
655,Rice University,0.982652,0.963073,0.760843,0.136307,0.889120
146,Georgia Institute of Technology-Main Campus,0.978934,0.935316,0.830235,0.057001,0.887831
53,University of California-San Diego,0.914498,0.922181,0.814126,0.603470,0.881561
122,University of Florida,0.962825,0.823916,0.970260,0.270136,0.881059
172,University of Chicago,0.993804,0.959851,0.684015,0.091698,0.874857
50,University of California-Irvine,0.924411,0.905328,0.713755,0.651797,0.861970

In [12]:
final_ranking = final_ranking.reset_index(drop=True)

final_ranking.index = final_ranking.index + 1

final_ranking.index.name = "RANK"

final_ranking

,INSTNM,STUDENT_SUCCESS_PERCENTILE,OUTCOME_SCORE,AFFORDABILITY_PERCENTILE,ACCESSIBILITY_PERCENTILE,FINAL_SCORE
RANK,,,,,,
1,Princeton University,1.000000,0.993804,0.971499,0.198265,0.952045
2,University of California-Berkeley,0.967782,0.968030,0.753408,0.455390,0.899374
3,University of California-Los Angeles,0.969021,0.919207,0.811029,0.442379,0.893656
4,Stanford University,0.966543,0.998513,0.737299,0.195787,0.893346
5,Rice University,0.982652,0.963073,0.760843,0.136307,0.889120
6,Georgia Institute of Technology-Main Campus,0.978934,0.935316,0.830235,0.057001,0.887831
7,University of California-San Diego,0.914498,0.922181,0.814126,0.603470,0.881561
8,University of Florida,0.962825,0.823916,0.970260,0.270136,0.881059
9,University of Chicago,0.993804,0.959851,0.684015,0.091698,0.874857
10,University of California-Irvine,0.924411,0.905328,0.713755,0.651797,0.861970

TO verify, I will change the weights to ensure nothing out of the ordinary comes up.

In [13]:
scenarios = {
    "baseline": [0.4, 0.35, 0.2, 0.05],
    "equal": [0.25, 0.25, 0.25, 0.25],
    "success": [0.5, 0.3, 0.15, 0.05],
    "outcome": [0.3, 0.45, 0.15, 0.1],
    "affordability": [0.3, 0.2, 0.4, 0.1],
    "accessibility": [0.2, 0.2, 0.2, 0.4]
}

for name, weights in scenarios.items():
  df[name] = (
    df["STUDENT_SUCCESS_PERCENTILE"] * weights[0]
    + df["OUTCOME_SCORE"] * weights[1]
    + df["AFFORDABILITY_PERCENTILE"] * weights[2]
    + df["ACCESSIBILITY_PERCENTILE"] * weights[3]
  )

In [21]:
baseline = (df.sort_values(
    "baseline", ascending = False
    ).head(10)[[
        "INSTNM",
        "STUDENT_SUCCESS_PERCENTILE",
        "OUTCOME_SCORE",
        "AFFORDABILITY_PERCENTILE",
        "ACCESSIBILITY_PERCENTILE",
        "baseline",
    ]]
    )

baseline

,INSTNM,STUDENT_SUCCESS_PERCENTILE,OUTCOME_SCORE,AFFORDABILITY_PERCENTILE,ACCESSIBILITY_PERCENTILE,baseline
393,Princeton University,1.000000,0.993804,0.971499,0.198265,0.952045
48,University of California-Berkeley,0.967782,0.968030,0.753408,0.455390,0.899374
51,University of California-Los Angeles,0.969021,0.919207,0.811029,0.442379,0.893656
760,Stanford University,0.966543,0.998513,0.737299,0.195787,0.893346
655,Rice University,0.982652,0.963073,0.760843,0.136307,0.889120
146,Georgia Institute of Technology-Main Campus,0.978934,0.935316,0.830235,0.057001,0.887831
53,University of California-San Diego,0.914498,0.922181,0.814126,0.603470,0.881561
122,University of Florida,0.962825,0.823916,0.970260,0.270136,0.881059
172,University of Chicago,0.993804,0.959851,0.684015,0.091698,0.874857
50,University of California-Irvine,0.924411,0.905328,0.713755,0.651797,0.861970

In [34]:
equal = (df.sort_values(
    "equal", ascending = False
    ).head(10)[[
        "INSTNM",
        "STUDENT_SUCCESS_PERCENTILE",
        "OUTCOME_SCORE",
        "AFFORDABILITY_PERCENTILE",
        "ACCESSIBILITY_PERCENTILE",
        "equal",
    ]]
    )

equal

,INSTNM,STUDENT_SUCCESS_PERCENTILE,OUTCOME_SCORE,AFFORDABILITY_PERCENTILE,ACCESSIBILITY_PERCENTILE,equal
416,CUNY Bernard M Baruch College,0.745973,0.904089,0.998761,0.919455,0.892069
42,California State University-Fullerton,0.696406,0.747955,0.969021,0.850062,0.815861
53,University of California-San Diego,0.914498,0.922181,0.814126,0.603470,0.813569
44,California State University-Long Beach,0.705081,0.774226,0.887237,0.869888,0.809108
38,California State Polytechnic University-Pomona,0.702602,0.836927,0.853779,0.836431,0.807435
419,CUNY City College,0.464684,0.820322,0.992565,0.934325,0.802974
780,University of California-Merced,0.669145,0.762330,0.836431,0.930607,0.799628
50,University of California-Irvine,0.924411,0.905328,0.713755,0.651797,0.798823
393,Princeton University,1.000000,0.993804,0.971499,0.198265,0.790892
420,CUNY Hunter College,0.448575,0.788104,1.000000,0.912020,0.787175

In [33]:
success = (df.sort_values(
    "success", ascending = False
    ).head(10)[[
        "INSTNM",
        "STUDENT_SUCCESS_PERCENTILE",
        "OUTCOME_SCORE",
        "AFFORDABILITY_PERCENTILE",
        "ACCESSIBILITY_PERCENTILE",
        "success",
    ]]
    )

success

,INSTNM,STUDENT_SUCCESS_PERCENTILE,OUTCOME_SCORE,AFFORDABILITY_PERCENTILE,ACCESSIBILITY_PERCENTILE,success
393,Princeton University,1.000000,0.993804,0.971499,0.198265,0.953779
48,University of California-Berkeley,0.967782,0.968030,0.753408,0.455390,0.910081
51,University of California-Los Angeles,0.969021,0.919207,0.811029,0.442379,0.904046
760,Stanford University,0.966543,0.998513,0.737299,0.195787,0.903209
655,Rice University,0.982652,0.963073,0.760843,0.136307,0.901190
146,Georgia Institute of Technology-Main Campus,0.978934,0.935316,0.830235,0.057001,0.897447
172,University of Chicago,0.993804,0.959851,0.684015,0.091698,0.892045
122,University of Florida,0.962825,0.823916,0.970260,0.270136,0.887633
53,University of California-San Diego,0.914498,0.922181,0.814126,0.603470,0.886196
635,Vanderbilt University,0.972739,0.960099,0.615861,0.224287,0.877993

In [32]:
outcome = (df.sort_values(
    "outcome", ascending = False
    ).head(10)[[
        "INSTNM",
        "STUDENT_SUCCESS_PERCENTILE",
        "OUTCOME_SCORE",
        "AFFORDABILITY_PERCENTILE",
        "ACCESSIBILITY_PERCENTILE",
        "outcome",
    ]]
    )

outcome

,INSTNM,STUDENT_SUCCESS_PERCENTILE,OUTCOME_SCORE,AFFORDABILITY_PERCENTILE,ACCESSIBILITY_PERCENTILE,outcome
393,Princeton University,1.000000,0.993804,0.971499,0.198265,0.912763
48,University of California-Berkeley,0.967782,0.968030,0.753408,0.455390,0.884498
416,CUNY Bernard M Baruch College,0.745973,0.904089,0.998761,0.919455,0.872392
53,University of California-San Diego,0.914498,0.922181,0.814126,0.603470,0.871797
51,University of California-Los Angeles,0.969021,0.919207,0.811029,0.442379,0.870242
760,Stanford University,0.966543,0.998513,0.737299,0.195787,0.869467
50,University of California-Irvine,0.924411,0.905328,0.713755,0.651797,0.856964
655,Rice University,0.982652,0.963073,0.760843,0.136307,0.855936
146,Georgia Institute of Technology-Main Campus,0.978934,0.935316,0.830235,0.057001,0.844808
49,University of California-Davis,0.903346,0.926394,0.687732,0.526642,0.843705

In [31]:
affordability = (df.sort_values(
    "affordability", ascending = False
    ).head(10)[[
        "INSTNM",
        "STUDENT_SUCCESS_PERCENTILE",
        "OUTCOME_SCORE",
        "AFFORDABILITY_PERCENTILE",
        "ACCESSIBILITY_PERCENTILE",
        "affordability",
    ]]
    )

affordability

,INSTNM,STUDENT_SUCCESS_PERCENTILE,OUTCOME_SCORE,AFFORDABILITY_PERCENTILE,ACCESSIBILITY_PERCENTILE,affordability
393,Princeton University,1.000000,0.993804,0.971499,0.198265,0.907187
416,CUNY Bernard M Baruch College,0.745973,0.904089,0.998761,0.919455,0.896059
122,University of Florida,0.962825,0.823916,0.970260,0.270136,0.868748
799,University of Florida-Online,0.902107,0.823916,0.985130,0.280050,0.857472
53,University of California-San Diego,0.914498,0.922181,0.814126,0.603470,0.844783
51,University of California-Los Angeles,0.969021,0.919207,0.811029,0.442379,0.843197
42,California State University-Fullerton,0.696406,0.747955,0.969021,0.850062,0.831128
48,University of California-Berkeley,0.967782,0.968030,0.753408,0.455390,0.830843
488,University of North Carolina at Chapel Hill,0.957869,0.848079,0.851301,0.218092,0.819306
146,Georgia Institute of Technology-Main Campus,0.978934,0.935316,0.830235,0.057001,0.818538

In [30]:
accessibility = (df.sort_values(
    "accessibility", ascending = False
    ).head(10)[[
        "INSTNM",
        "STUDENT_SUCCESS_PERCENTILE",
        "OUTCOME_SCORE",
        "AFFORDABILITY_PERCENTILE",
        "ACCESSIBILITY_PERCENTILE",
        "accessibility",
    ]]
    )

accessibility

,INSTNM,STUDENT_SUCCESS_PERCENTILE,OUTCOME_SCORE,AFFORDABILITY_PERCENTILE,ACCESSIBILITY_PERCENTILE,accessibility
416,CUNY Bernard M Baruch College,0.745973,0.904089,0.998761,0.919455,0.897546
419,CUNY City College,0.464684,0.820322,0.992565,0.934325,0.829244
780,University of California-Merced,0.669145,0.762330,0.836431,0.930607,0.825824
42,California State University-Fullerton,0.696406,0.747955,0.969021,0.850062,0.822701
44,California State University-Long Beach,0.705081,0.774226,0.887237,0.869888,0.821264
38,California State Polytechnic University-Pomona,0.702602,0.836927,0.853779,0.836431,0.813234
420,CUNY Hunter College,0.448575,0.788104,1.000000,0.912020,0.812144
417,CUNY Brooklyn College,0.406444,0.745725,0.997522,0.921933,0.798711
41,California State University-Fresno,0.485750,0.698637,0.966543,0.920694,0.798463
421,CUNY John Jay College of Criminal Justice,0.465923,0.646592,0.995043,0.931846,0.794250