<a href="https://colab.research.google.com/github/DanielYaari28/AIPI510P1/blob/daniel-final-ranking/notebooks/03_final_ranking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd

url = "https://raw.githubusercontent.com/DanielYaari28/AIPI510P1/refs/heads/main/data/engineered_college_data.csv"
df = pd.read_csv(url)

In [6]:
df.columns

Index(['UNITID', 'INSTNM', 'STABBR', 'CONTROL', 'UGDS', 'C150_4', 'RET_FT4',
       'NPT4_PUB', 'NPT4_PRIV', 'DEBT_MDN', 'COSTT4_A', 'MD_EARN_WNE_P10',
       'PCTPELL', 'ADM_RATE', 'NET_PRICE', 'STUDENT_SUCCESS',
       'DEBT_TO_EARNINGS', 'EARNINGS_PERCENTILE', 'DEBT_BURDEN_PERCENTILE',
       'OUTCOME_SCORE', 'AFFORDABILITY_PERCENTILE',
       'ACCESSIBILITY_PERCENTILE'],
      dtype='object')

In [7]:
df["STUDENT_SUCCESS_PERCENTILE"] = df["STUDENT_SUCCESS"].rank(
    pct=True,
    ascending=True
)

In [31]:
df["FINAL_SCORE"] = (
    df["STUDENT_SUCCESS_PERCENTILE"] * 0.40
    + df["OUTCOME_SCORE"] * 0.35
    + df["AFFORDABILITY_PERCENTILE"] * 0.20
    + df["ACCESSIBILITY_PERCENTILE"] * 0.05
)

In [33]:
final_ranking = (
    df
    .sort_values("FINAL_SCORE", ascending=False)
    .head(10)
    [[
        "INSTNM",
        "STUDENT_SUCCESS_PERCENTILE",
        "OUTCOME_SCORE",
        "AFFORDABILITY_PERCENTILE",
        "ACCESSIBILITY_PERCENTILE",
        "FINAL_SCORE"
    ]]
)

final_ranking

,INSTNM,STUDENT_SUCCESS_PERCENTILE,OUTCOME_SCORE,AFFORDABILITY_PERCENTILE,ACCESSIBILITY_PERCENTILE,FINAL_SCORE
393,Princeton University,1.000000,0.993804,0.971499,0.198265,0.952045
48,University of California-Berkeley,0.967782,0.968030,0.753408,0.455390,0.899374
51,University of California-Los Angeles,0.969021,0.919207,0.811029,0.442379,0.893656
760,Stanford University,0.966543,0.998513,0.737299,0.195787,0.893346
655,Rice University,0.982652,0.963073,0.760843,0.136307,0.889120
146,Georgia Institute of Technology-Main Campus,0.978934,0.935316,0.830235,0.057001,0.887831
53,University of California-San Diego,0.914498,0.922181,0.814126,0.603470,0.881561
122,University of Florida,0.962825,0.823916,0.970260,0.270136,0.881059
172,University of Chicago,0.993804,0.959851,0.684015,0.091698,0.874857
50,University of California-Irvine,0.924411,0.905328,0.713755,0.651797,0.861970

In [34]:
final_ranking = final_ranking.reset_index(drop=True)

final_ranking.index = final_ranking.index + 1

final_ranking.index.name = "RANK"

final_ranking

,INSTNM,STUDENT_SUCCESS_PERCENTILE,OUTCOME_SCORE,AFFORDABILITY_PERCENTILE,ACCESSIBILITY_PERCENTILE,FINAL_SCORE
RANK,,,,,,
1,Princeton University,1.000000,0.993804,0.971499,0.198265,0.952045
2,University of California-Berkeley,0.967782,0.968030,0.753408,0.455390,0.899374
3,University of California-Los Angeles,0.969021,0.919207,0.811029,0.442379,0.893656
4,Stanford University,0.966543,0.998513,0.737299,0.195787,0.893346
5,Rice University,0.982652,0.963073,0.760843,0.136307,0.889120
6,Georgia Institute of Technology-Main Campus,0.978934,0.935316,0.830235,0.057001,0.887831
7,University of California-San Diego,0.914498,0.922181,0.814126,0.603470,0.881561
8,University of Florida,0.962825,0.823916,0.970260,0.270136,0.881059
9,University of Chicago,0.993804,0.959851,0.684015,0.091698,0.874857
10,University of California-Irvine,0.924411,0.905328,0.713755,0.651797,0.861970